### ISSUE TITLE
More participants and transactions

### ISSUE THREAD

**Issue by zipweight** [worldsibu/convector-identity-patterns#1]
implementing `authentication` is complex for me, and I believe that everything can be simplified with an example, but this example's a bit too simple, i think it should have more `participants` and `transactions`
or if there's a `backend`&`frontend` like the "drug-supply" example https://github.com/worldsibu/convector-example-drug-supply-chain

"drug-supply" example is great and understandable because its implementation is more close to a real application
but unfortunately it doesn't have "authentication" implementation..
  
thank you

**Comment by walmon** [comment]
I added more participants and a transfer extra function. Check it out in the README. Beware that it uses Hurley `0.5.1` which brings breaking changes on the invoke function. a1ed71c1d4e885e6503e6da6949b258316f83c28

We won't add a backend and frontend to it since it's not the goal of the repo. It's better to update that supply change example or create a new one for that matter.

**Comment by walmon** [comment]
I've implemented the pattern here as well: https://github.com/worldsibu/convector-example-drug-supply-chain
